#!/bin/sh

LANIP=192.168.12.1
LANIP6=fd00:100:120::1
LANIP6PRE=fd00:100:120::/48
WIFI1=OpenWrt
WIFI2=${WIFI1}-5G
WPASS=88888888

#LANIP=100.127.64.1
#LANIP6=fd00:100:200::1
#LANIP6PRE=fd00:100:200::/48
#WIFI1=TP-LINK_888
#WIFI2=${WIFI1}-5G
#WPASS=88888888

uci set luci.main.lang=zh_cn
# uci set luci.main.mediaurlbase=Bootstap
uci commit luci

uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system

uci set fstab.@global[0].anon_mount=1
uci commit fstab

################################
uci set wireless.default_radio0.disassoc_low_ack=0

uci set wireless.@wifi-device[0].disabled=0
uci set wireless.@wifi-device[0].txpower=17
uci set wireless.@wifi-device[0].hwmode=11g
uci set wireless.@wifi-device[0].channel=auto
uci set wireless.@wifi-device[0].country=CN
uci set wireless.@wifi-device[0].htmode=HT40
uci set wireless.@wifi-device[0].legacy_rates=1
uci set wireless.@wifi-device[0].noscan=1

uci set wireless.@wifi-iface[0].network=lan
uci set wireless.@wifi-iface[0].mode=ap
uci set wireless.@wifi-iface[0].ssid=$WIFI1
uci set wireless.@wifi-iface[0].encryption=psk2+ccmp
uci set wireless.@wifi-iface[0].key=$WPASS

# 5G wifi
uci set wireless.default_radio1.ssid=$WIFI2
uci set wireless.default_radio1.encryption=psk2+ccmp
uci set wireless.default_radio1.key=$WPASS

uci commit wireless

#local lan ip address
uci set network.lan.ipaddr=$LANIP
# IPv6 ula_prefix
uci set network.globals.ula_prefix=$LANIP6PRE
uci commit network

################################
# mirror of openwrt
sed -i 's/downloads.openwrt.org/mirrors.tuna.tsinghua.edu.cn\/openwrt/g' /etc/opkg/distfeeds.conf
# sed -i 's/downloads.openwrt.org/openwrt.proxy.ustclug.org/g' /etc/opkg/distfeeds.conf
# sed -i 's/root::0:0:99999:7:::/root:$1$BuM.Ox4e$X/RX2ftRaBzzVzoL6TkI0/:0:0:99999:7:::/g' /etc/shadow

# sed -i "s/# //g" /etc/opkg/distfeeds.conf


# IPv6 ula_prefix
#sed -i "s/option ula_prefix.*/option ula_prefix 'fd00:100:100::\/48'/" /etc/config/network

uci set dhcp.lan.ra='server'
uci set dhcp.lan.dhcpv6='server'
uci set dhcp.lan.ra_management='1'
uci set dhcp.lan.ra_default='1'
uci commit dhcp
#/etc/init.d/network restart

#sed -i '/REDIRECT --to-ports 53/d' /etc/firewall.user
#echo "iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53" >> /etc/firewall.user
#echo "iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53" >> /etc/firewall.user

sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh
wifi up

#IPv6 NAT
egrep -q  "ip6tables -A FORWARD -i br-lan -j ACCEPT"      /etc/firewall ||
	echo  "ip6tables -A FORWARD -i br-lan -j ACCEPT"   >> /etc/firewall.user

egrep -q  "ip6tables -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT" /etc/firewall.user ||
	echo  "ip6tables -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT" >> /etc/firewall.user

egrep -q  "ip6tables -t nat -A POSTROUTING -s $LANIP6PRE -j MASQUERADE"  /etc/firewall.user ||
	echo  "ip6tables -t nat -A POSTROUTING -s $LANIP6PRE -j MASQUERADE" >> /etc/firewall.user

#dnsmasq setting
egrep -q "localise-queries"  /etc/dnsmasq.conf ||
	echo "localise-queries" >> /etc/dnsmasq.conf

egrep -q "bogus-priv"  /etc/dnsmasq.conf ||
	echo "bogus-priv" >> /etc/dnsmasq.conf

egrep -q  "expand-hosts"  /etc/dnsmasq.conf ||
	echo  "expand-hosts" >> /etc/dnsmasq.conf

egrep -q  "srv-host=_vlmcs._tcp.lan,OpenWrt.lan,1688,0,100"  /etc/dnsmasq.conf ||
	echo  "srv-host=_vlmcs._tcp.lan,OpenWrt.lan,1688,0,100" >> /etc/dnsmasq.conf


#vlmcsd
uci set vlmcsd.config.autoactivate=1
uci commit vlmcsd

#Add /etc/hosts item
sed -i -re '/(^|\s)gw(\s|$)/d' /etc/hosts
echo "$LANIP				gw			fw" >> /etc/hosts
sed -i -re '/(^|\s)gw6(\s|$)/d' /etc/hosts
echo "$LANIP6				gw6			fw6" >> /etc/hosts

#cron command
egrep -q  "30 4 * * * sleep 70 && touch /etc/banner && reboot "    /etc/crontabs/root ||
	echo  "30 4 * * * sleep 70 && touch /etc/banner && reboot "   >> /etc/crontabs/root
/etc/init.d/cron    restart

#default, disable mwan3( for ipv6)
/etc/init.d/mwan3 disable

#before exit, restart service
/etc/init.d/network restart
/etc/init.d/dnsmasq restart

#reboot

exit 0

