#!/bin/sh

uci set luci.main.lang=zh_cn
# uci set luci.main.mediaurlbase=Bootstap
uci commit luci

uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system

uci set fstab.@global[0].anon_mount=1
uci commit fstab

################################
uci set wireless.default_radio0.disassoc_low_ack=0

uci set wireless.@wifi-device[0].disabled=0
uci set wireless.@wifi-device[0].txpower=17
uci set wireless.@wifi-device[0].hwmode=11g
uci set wireless.@wifi-device[0].channel=auto
uci set wireless.@wifi-device[0].country=CN
uci set wireless.@wifi-device[0].htmode=HT40
uci set wireless.@wifi-device[0].legacy_rates=1
uci set wireless.@wifi-device[0].noscan=1

uci set wireless.@wifi-iface[0].network=lan
uci set wireless.@wifi-iface[0].mode=ap
uci set wireless.@wifi-iface[0].ssid=TP-LINK_DJK888
uci set wireless.@wifi-iface[0].encryption=psk2+ccmp
uci set wireless.@wifi-iface[0].key=123

# 5G wifi
uci set wireless.default_radio1.ssid=TP-LINK-DJK888-5G
uci set wireless.default_radio1.encryption=psk2+ccmp
uci set wireless.default_radio1.key=123

uci commit wireless

#local lan ip address
uci set network.lan.ipaddr=192.168.20.1
# IPv6 ula_prefix
uci set network.globals.ula_prefix=fd00:100:100::/48
uci commit network

################################

# sed -i 's/downloads.openwrt.org/openwrt.proxy.ustclug.org/g' /etc/opkg/distfeeds.conf
# sed -i 's/root::0:0:99999:7:::/root:$1$BuM.Ox4e$X/RX2ftRaBzzVzoL6TkI0/:0:0:99999:7:::/g' /etc/shadow

# sed -i "s/# //g" /etc/opkg/distfeeds.conf


# IPv6 ula_prefix
#sed -i "s/option ula_prefix.*/option ula_prefix 'fd00:100:100::\/48'/" /etc/config/network

uci set dhcp.lan.ra='server'
uci set dhcp.lan.dhcpv6='server'
uci set dhcp.lan.ra_management='1'
uci set dhcp.lan.ra_default='1'
uci commit dhcp
#/etc/init.d/network restart

sed -i '/REDIRECT --to-ports 53/d' /etc/firewall.user
echo "iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53" >> /etc/firewall.user
echo "iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53" >> /etc/firewall.user

sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh
wifi up

#IPv6 NAT
echo "ip6tables -A FORWARD -i br-lan -j ACCEPT"   >> /etc/firewall.user
echo "ip6tables -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT" >> /etc/firewall.user
echo "ip6tables -t nat -A POSTROUTING -s fd00:100:100::/48 -j MASQUERADE" >> /etc/firewall.user

#dnsmasq setting
echo "localise-queries" >> /etc/dnsmasq.conf
echo "bogus-priv" >> /etc/dnsmasq.conf
echo "expand-hosts" >> /etc/dnsmasq.conf
echo "srv-host=_vlmcs._tcp.lan,OpenWrt.lan,1688,0,100" >> /etc/dnsmasq.conf
echo "" >> /etc/dnsmasq.conf

#vlmcsd
uci set vlmcsd.config.autoactivate=1
uci commit vlmcsd

#Add /etc/hosts item
echo "192.168.20.1				gw" >> /etc/hosts
echo "fd00:100:100::1			gw" >> /etc/hosts

#cron command
echo "30 4 * * * sleep 70 && touch /etc/banner && reboot "   >> /etc/crontabs/root
/etc/init.d/cron    restart

#default, disable mwan3( for ipv6)
/etc/init.d/mwan3 disable

#before exit, restart service
/etc/init.d/network restart
/etc/init.d/dnsmasq restart

#reboot

exit 0

